---
minimum_pre_commit_version: 3.0.0
repos:
  - repo: local
    hooks:
      - id: pipenv-lock-verify
        name: pipenv-lock-verify
        files: Pipfile|Pipfile.lock
        entry: pipenv verify
        pass_filenames: false
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        exclude: ^docs/
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [html, json, yaml, toml, markdown, javascript]
        additional_dependencies:
          - prettier@2.2.0
          - prettier-plugin-toml@0.3.1
